# Generated by Django 3.2.7 on 2021-10-02 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('c4app', '0003_auto_20211003_0013'),
    ]

    operations = [
        migrations.DeleteModel(
            name='orders',
        ),
    ]
